### PR TITLE
Remove Attach rpc request

### LINKED ISSUE #2237: Remove attach rpc request
The attach request is no longer needed and can be removed https://github.com/restatedev/restate/blob/3a293a4e402a22402ca3895c6bb9c41002d9c040/crates/worker/src/partition_processor_manager.rs#L460

### PR DESCRIPTION
**Pull request by muhamadazmy**
Remove Attach rpc request

Fixes #2237

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2250).
* #2252
* __->__ #2250

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
LGTM. +1 for merging.

**Comment by tillrohrmann** [comment]
Maybe check why the distributed test fails. Might one of the reasons I've listed here #2248.

**Comment by AhmedSoliman** [comment]
Anything blocking this from merge?

**Comment by tillrohrmann** [comment]
Should be good to be merged now. Modulo the merge conflicts that I caused. I apologize for this 🙇

**Comment by muhamadazmy** [comment]
@tillrohrmann thank you for your review and input. No worries about the merge conflict 😉

**Pull request merged**
