### PR TITLE
Little improvement to handlers Input/output types that are printed during registration.

### PR DESCRIPTION
**Pull request by slinkydeveloper**

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
Can you include a screenshot or example output in the PR description?

**Comment by slinkydeveloper** [comment]
Just a little change to print nicely the INPUT/OUTPUT:

```
📜 Service Information:
―――――――――――――――――――――――
 Name:             counter                        
 Service type:     VirtualObject                  
 Revision:         1                              
 Public:           true                           
 Deployment ID:    dp_16QM98gLjRl5K0OEXv9Wfh7     
 Deployment Type:  HTTP 2                         
 Protocol Style:   Streaming                      
 Endpoint:         http://localhost:9080/         
 Created at:       2024-04-23T15:28:11.992000000Z 


🔌 Handlers:
――――――――――――
 HANDLER  INPUT                                           OUTPUT                                   
 count    one of ["none", "value of content-type '*/*'"]  value of content-type 'application/json' 
```

We'll fill those INPUT/OUTPUT in future with more interesting details.

**Comment by slinkydeveloper** [comment]
For Java/Kotlin, where we have more metadata about the handlers due to compile time code generation, we print the following:

```
❯ SERVICES THAT WILL BE ADDED:
  - CounterKt
    Type: VirtualObject ⬅️ 🚶🚶🚶
     HANDLER    INPUT                                     OUTPUT                                   
     getAndAdd  value of content-type 'application/json'  value of content-type 'application/json' 
     get        none                                      value of content-type 'application/json' 
     reset      none                                      none                                     
     add        value of content-type 'application/json'  none                                     


```

**Comment by AhmedSoliman** [comment]
I'm not sure if `value of content-type 'application/json' or `one of ["none", "value of content-type '*/*'"]` is really meaningful to users, also a bit long?

**Review by tillrohrmann — APPROVED** [review]
Yeah, ideally we can provide some more concrete schema information for the input and output types. I think this is also the plan for the future. Technically, this PR didn't introduce these things but it improves the formatting. So +1 for merging them.

**Pull request merged**
