### PR TITLE
Allow Bifrost to modify Logs in case of missing Chains

### PR DESCRIPTION
**Pull request by tillrohrmann**
This commit allows Bifrost to update the Logs configuration
in case a missing Chain for a given LogId is detected. In this
case, the Bifrost client tries to update the Logs configuration
with its configured default provider.

This fixes https://github.com/restatedev/restate/issues/1341.

This PR is based on #1338.

@AhmedSoliman let me know if this commit goes against the ideas you had for Bifrost.

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
I'm not sure we should auto provision log-ids implicitly on appends. Provisioning logs should happen only during partition split or merge. I can think of many risks to this approach, too many to enumerate actually :D

**Comment by tillrohrmann** [comment]
Fair point. 

What's currently not very intuitive is that the `default_provider` in Bifrost's options is not respected when explicitly creating a Bifrost service in tests when using the `TestCoreEnv` because `TestCoreEnv` initializes the `Logs` based on the `PartitionTable` (similar to what the node does on normal startup). One simple solution could then be to make the `ProviderKind` configurable when creating the `TestCoreEnv`.

**Comment by AhmedSoliman** [comment]
Should we close this one then?

**Comment by tillrohrmann** [comment]
Jup. Closing as too dangerous.

**Pull request closed without merging**
