### PR TITLE
feat: update pgwire to latest release

### PR DESCRIPTION
**Pull request by sunng87**
pgwire author here. This patch just updates pgwire library and adopt its breaking API changes.

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
Thanks a lot for your contribution @sunng87. The changes look good to me :-) I will try them out locally and then merge this PR.

**Comment by tillrohrmann** [comment]
I've tested this change locally with `psql (PostgreSQL) 16.3 (Homebrew)` and it worked nicely. Running now CI and merging once this gives green light.

**Comment by sunng87** [comment]
Thank you @tillrohrmann . Feel free to discuss with me when you find anything interesting to implement with postgres wire protocol.

**Comment by tillrohrmann** [comment]
> Thank you @tillrohrmann . Feel free to discuss with me when you find anything interesting to implement with postgres wire protocol.

Awesome. Good to know that we can reach out :-)

**Pull request merged**
