### PR TITLE
Set nodelay on http client

### PR DESCRIPTION
**Pull request by jackkleeman**
For perf testing to determine if useful

### CODE REVIEW

**Review by tillrohrmann — COMMENTED** [review]
If this is only meant for perf testing and not shipping it, I would suggest that we either first measure whether it makes a difference or make it configurable so that one can enable it for perf testing.

**Comment by jackkleeman** [comment]
@tillrohrmann this PR is so that ahmed can test it, if he sees no benefit I will close it!

**Comment by tillrohrmann** [comment]
Thanks for the clarification.

**Comment by AhmedSoliman** [comment]
My changes now incorporate this already. Thanks Jack for suggesting this change.

**Pull request closed without merging**
