### PR TITLE
Delete the node dir when wiping all

### PR DESCRIPTION
**Pull request by tillrohrmann**
WipeMode::All will now delete the whole node base dir to also
remove a cluster marker file.

This fixes https://github.com/restatedev/restate/issues/1629.

This PR is based on #1628.

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
I wonder if we should go the opposite way and completely remove the wipe command. It might be better to ask users to remove (or rename) the data directory instead of providing this as a feature. What do you think?

**Comment by tillrohrmann** [comment]
> I wonder if we should go the opposite way and completely remove the wipe command. It might be better to ask users to remove (or rename) the data directory instead of providing this as a feature. What do you think?

It is certainly a foot gun and trains people in bad habits. Maybe I only fix it then in the `release-1.0` branch where we still have the wipe command and remove the wipe command in `main`?

**Comment by AhmedSoliman** [comment]
@tillrohrmann up to you.

**Review by AhmedSoliman — APPROVED** [review]

**Comment by tillrohrmann** [comment]
The respective issue for removing/hiding the wipe command is https://github.com/restatedev/restate/issues/1650.

**Pull request merged**
